apiVersion: v1
kind: Service
metadata: 
  name: php-desafio
spec:
  selector:
    app: php-desafio
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-desafio
  clusterIP: None